using System.Text.Json;
using CodexQuotaFloat.Models;
using CodexQuotaFloat.Services;
using CodexQuotaFloat.ViewModels;
namespace CodexQuotaFloat.Tests;
public sealed class UsageParserTests
{
    [Fact] public void PrefersCodexAndClassifiesWindows() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":300,"usedPercent":28,"resetsAt":1},"secondary":{"windowDurationMins":10080,"usedPercent":52,"resetsAt":2}},"codex_other":{"primary":{"windowDurationMins":300,"usedPercent":99}}}}"""); var actual = UsageParser.Parse(doc.RootElement); Assert.Equal(72, actual.FiveHour.RemainingPercent); Assert.Equal(48, actual.Weekly.RemainingPercent); }
    [Theory] [InlineData(-5,100)] [InlineData(110,0)] public void ClampsRemaining(double used, int expected) { var json = "{\"rateLimits\":{\"limitId\":\"codex\",\"primary\":{\"windowDurationMins\":300,\"usedPercent\":" + used + "}}}"; using var doc = JsonDocument.Parse(json); Assert.Equal(expected, UsageParser.Parse(doc.RootElement).FiveHour.RemainingPercent); }
    [Fact] public void WeeklyOnlyMakesFiveHourUnlimited() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":10080,"usedPercent":14,"resetsAt":2}}}}"""); var actual = UsageParser.Parse(doc.RootElement); Assert.Equal(RateLimitAvailability.Unlimited, actual.FiveHour.Availability); Assert.Equal(86, actual.Weekly.RemainingPercent); Assert.True(actual.IsStructureSupported); }
    [Fact] public void MissingWeeklyIsUnavailableNotUnlimited() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","primary":{"windowDurationMins":300,"usedPercent":10}}}"""); var actual = UsageParser.Parse(doc.RootElement); Assert.Equal(RateLimitAvailability.Unavailable, actual.Weekly.Availability); }
    [Fact] public void RestoredFiveHourBecomesAvailable() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","primary":{"windowDurationMins":300,"usedPercent":10},"secondary":{"windowDurationMins":10080,"usedPercent":20}}}"""); Assert.Equal(RateLimitAvailability.Available, UsageParser.Parse(doc.RootElement).FiveHour.Availability); }
    [Fact] public void NoBucketIsNotSupported() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"other":{}}}"""); var actual = UsageParser.Parse(doc.RootElement); Assert.False(actual.HasCodexBucket); Assert.False(actual.IsStructureSupported); }
    [Fact] public void KnownWindowsWithoutUsedPercentAreUnsupported() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","primary":{"windowDurationMins":300}}}"""); Assert.False(UsageParser.Parse(doc.RootElement).IsStructureSupported); }
    [Fact] public void MissingResetKeepsPercentage() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","primary":{"windowDurationMins":300,"usedPercent":10},"secondary":{"windowDurationMins":10080,"usedPercent":20}}}"""); var actual = UsageParser.Parse(doc.RootElement); Assert.Equal(90, actual.FiveHour.RemainingPercent); Assert.Null(actual.FiveHour.ResetsAt); }
    [Fact] public void UnknownWindowDoesNotBreakParsing() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","future":{"windowDurationMins":720,"usedPercent":20},"secondary":{"windowDurationMins":10080,"usedPercent":20}}}"""); Assert.Contains(720, UsageParser.Parse(doc.RootElement).UnknownWindowDurations); }
    [Fact] public void LegacyCodexBucketIsAccepted() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","primary":{"windowDurationMins":10080,"usedPercent":20}}}"""); Assert.True(UsageParser.Parse(doc.RootElement).HasCodexBucket); }
    [Fact] public void NonCodexLegacyBucketIsIgnored() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"other","primary":{"windowDurationMins":10080,"usedPercent":20}}}"""); Assert.False(UsageParser.Parse(doc.RootElement).HasCodexBucket); }
    [Fact] public void NestedFutureWindowIsFound() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","future":{"nested":{"windowDurationMins":10080,"usedPercent":20}}}}"""); Assert.Equal(80, UsageParser.Parse(doc.RootElement).Weekly.RemainingPercent); }
    [Fact] public void ParsesPositiveBankedResetCount() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":10080,"usedPercent":20},"banked_reset_count":3}}}"""); Assert.Equal(3, UsageParser.Parse(doc.RootElement).BankedResetCount); }
    [Fact] public void ParsesZeroBankedResetCount() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":10080,"usedPercent":20},"bankedResets":0}}}"""); Assert.Equal(0, UsageParser.Parse(doc.RootElement).BankedResetCount); }
    [Fact] public void ParsesAppServerRateLimitResetCreditAvailableCount() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":10080,"usedPercent":20}}},"rateLimitResetCredits":{"availableCount":1,"credits":null}}"""); Assert.Equal(1, UsageParser.Parse(doc.RootElement).BankedResetCount); }
    [Fact] public void ParsesNestedResetCreditAvailableCount() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","primary":{"windowDurationMins":10080,"usedPercent":20}},"account":{"entitlements":{"resetCredits":{"availableCount":2}}}}"""); Assert.Equal(2, UsageParser.Parse(doc.RootElement).BankedResetCount); }
    [Fact] public void ParsesResetCreditsInArray() { using var doc = JsonDocument.Parse("""{"rateLimits":{"limitId":"codex","primary":{"windowDurationMins":10080,"usedPercent":20}},"items":[{"resetCredits":{"availableCount":3}}]}"""); Assert.Equal(3, UsageParser.Parse(doc.RootElement).BankedResetCount); }
    [Fact] public void MissingBankedResetCountDoesNotBreakQuotaParsing() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":10080,"usedPercent":20}}}}"""); var snapshot = UsageParser.Parse(doc.RootElement); Assert.Null(snapshot.BankedResetCount); Assert.Equal(80, snapshot.Weekly.RemainingPercent); }
    [Fact] public void MalformedBankedResetCountFallsBackToUnknown() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":10080,"usedPercent":20},"banked_reset_count":"many"}}}"""); Assert.Null(UsageParser.Parse(doc.RootElement).BankedResetCount); }
    [Fact] public void BooleanResetAvailabilityDoesNotPretendToBeCount() { using var doc = JsonDocument.Parse("""{"rateLimitsByLimitId":{"codex":{"primary":{"windowDurationMins":10080,"usedPercent":20}}},"rateLimitResetCredits":{"hasCredits":true}}"""); Assert.Null(UsageParser.Parse(doc.RootElement).BankedResetCount); }
    [Fact] public void UnlimitedFormatsAsShortChineseLabel() => Assert.Equal("不限", FloatingViewModel.FormatWindowValue(RateLimitWindow.Unlimited(300)));
    [Fact] public void UnavailableFormatsAsTemporarilyUnavailable() => Assert.Equal("暂不可用", FloatingViewModel.FormatWindowValue(RateLimitWindow.Unavailable(10080)));
    [Theory] [InlineData(4, "4 次")] [InlineData(0, "0 次")] public void BankedResetDisplayFormatsKnownCounts(int count, string expected) => Assert.Equal(expected, FloatingViewModel.FormatBankedResetCount(count));
    [Fact] public void BankedResetDisplayFormatsUnknown() => Assert.Equal("--", FloatingViewModel.FormatBankedResetCount(null));
}
